---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: students
spec:
  selector:
    matchLabels:
      app: students
  replicas: 1
  template:
    metadata:
      labels:
        app: students
    spec:
      volumes:
      - name: myvol
        emptyDir: {}
      serviceAccountName: default
      containers:
        - name: students
          volumeMounts:
          - mountPath: /tmp
            name: myvol
          image: okn77/sample-service:v1
          imagePullPolicy: "Always"
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: true
   
   
   
 

---   
