---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: students
spec:
  selector:
    matchLabels:
      app: students
  replicas: 1
  template:
    metadata:
      labels:
        app: students
    spec:
      containers:
        - name: students
          image: okn77/sample-service:v1
          imagePullPolicy: "Always"
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: true
   
   
   
 

---   

  
   
apiVersion: v1
kind: Service
metadata:
  name: students
  labels:
    name: students
spec:
  type: NodePort
  selector:
    app: students
  ports:
  - name: students
    protocol: TCP
    port: 4444
    targetPort: 4444