  
   
apiVersion: v1
kind: Service
metadata:
  name: students
  namespace: prod
  labels:
    name: students
spec:
  type: NodePort
  selector:
    app: students
  ports:
  - name: students
    protocol: TCP
    port: 4444
    targetPort: 4444